flucoma/flucoma-docs

script/templates/pd_htmlref.html

fixes #16 
Adds a simple `<ol>` to give enum options

Add enum details to PD template

---

doc/KDTree.yaml

This removes the sklearn link fom the kdtree documentation.
The link is not only unclickable in many environments, but it should be shifted to higher level discussion on the learn.
This change is consistent with discussions we had _before_ Basel about how the documentation granularity should be shifted.﻿

KDTree Description

---

CMakeLists.txt

@jamesb93 does this fix the M1 build for you? 
One source of complication might be that if your CMake is x64 then it might try and set the arch to that (but passing directly to CMake should fix this...)

Don't bake in the architecture for apple

---

flucoma/doc/sc/driver.py

* FFT settings needed to be disaggregated into win, hop, fft. A remaining todo is how to have SC, Max and PD still use the same basic doc. At the moment we have duplication (SC is taken from the YAML now) 
* `padding` needed to be moved to the end of the parameter list (fixes #43)

Fix SC fft settings and  padding parameters

---

flucoma/doc/max/driver.py

Now we have a `species` key in the YAML, can do this more robustly and more simply 
fixes #11

Max: ensure all libmanipulation objects appear in `max.db.json`

---

doc/BufAudioTransport.yaml

Because this affects (at least) 3 of our repos, I thought it would be good to get everyone's eyes over it!
This converts BufAudioTransport's arguments to an A/B based system for the two input buffers. I tested this and it all seems to be working great.
In response to: https://github.com/flucoma/flucoma-docs/issues/66
Parallel to: 
* https://github.com/flucoma/flucoma-sc/pull/62
* https://github.com/flucoma/flucoma-core/pull/89

BufAudioTransport now has A-B based arguments

---

doc/Pitch.yaml
flucoma/doc/templates/maxref.xml
flucoma/doc/templates/pd_htmlref.html
flucoma/doc/transformers.py

This enables you to define:
```yaml
max-seealso: fzero~
pd-related: sigmund~
```
in the YAML docs which is then rendered in the appropriate templates.
I've opted for a relatively permissive `try/Except` block to catch cases where these new things are not defined or just not needed. It thusly throws a warning if they aren't which given the current unfinished state of the docs is a bit noisy.
On another note does this block up the YAML to RST milestone?

[Enhance] Add CCE specific see also sections to transformer and template

---

doc/BufMelBands.rst
doc/MelBands.rst

In response to: https://github.com/flucoma/flucoma-core/issues/84
Please read the added text and provide comments or approve.
This adds an explanation into the documentation. It doesn't throw an issue when it happens (as was discussed in the issue).
I think this can happen for beta5 and having the `C++` throw a warning when it happens can be saved for later when that becomes possible.

MelBands zeros warning

---

doc/AudioTransport.rst
doc/BufAudioTransport.rst

1. Separates out the very long description into the discussion + description
2. Adds a link to the DaFX paper

[Docs] AudioTransport

---

doc/BufMFCC.rst
doc/MFCC.rst
example-code/sc/BufMFCC.scd
example-code/sc/MFCC.scd

I think it would be great to have one more example for the BufMFCC SC help file. If anyone can think of an interesting thing to do for it, that would be great!

Mfcc helpfile & sc example

---

doc/Normalize.rst

Updated the normalize help file to be a little more consistent with how things have been named else where (points versus entries for example). @tremblap if you can take a once over that'd be great.
- update normalize entry
- update description

[Docs] Update Normalize Docs

---

doc/AmpFeature.rst
doc/BufAmpFeature.rst
doc/BufNoveltyFeature.rst
doc/BufNoveltySlice.rst
doc/BufOnsetFeature.rst
doc/NoveltyFeature.rst
doc/NoveltySlice.rst
doc/OnsetFeature.rst
example-code/sc/AmpFeature.scd
example-code/sc/BufAmpFeature.scd
example-code/sc/BufNoveltyFeature.scd
example-code/sc/BufOnsetFeature.scd
example-code/sc/NoveltyFeature.scd
example-code/sc/OnsetFeature.scd
src/clients/AmpFeature/AmpFeature.cpp
src/clients/AmpFeature/CMakeLists.txt
src/clients/BufAmpFeature/BufAmpFeature.cpp
src/clients/BufAmpFeature/CMakeLists.txt
src/clients/BufNoveltyFeature/BufNoveltyFeature.cpp
src/clients/BufNoveltyFeature/CMakeLists.txt
src/clients/BufOnsetFeature/BufOnsetFeature.cpp
src/clients/BufOnsetFeature/CMakeLists.txt
src/clients/NoveltyFeature/CMakeLists.txt
src/clients/NoveltyFeature/NoveltyFeature.cpp
src/clients/OnsetFeature/CMakeLists.txt
src/clients/OnsetFeature/OnsetFeature.cpp

Adds RST documentation for the new objects that produces features that the slicing objects use.﻿

[Docs] Slicer Feature Objects

---

flucoma/doc/cli/driver.py
flucoma/doc/max/driver.py
flucoma/doc/pd/driver.py
flucoma/doc/sc/driver.py
include/FluidParameterDump.hpp

https://github.com/flucoma/flucoma-core/pull/108

ParamDump and python: add choices param type

---

doc/BufMFCC.rst
doc/MFCC.rst

Much of the discussion was in the description for BufMFCC. This PR makes BufMFCC more similar to MFCC which will as a result also now render much much better in Max.

[Docs] MFCC and BufMFCC Harmonisation

---

doc/BufHPSS.rst
doc/HPSS.rst
example-code/sc/BufHPSS.scd
example-code/sc/HPSS.scd

If anyone has a really keen `maskingMode` = 2 example that'd be useful!

HPSS Help file (RST) and SC examples

---

doc/NMFMorph.rst
example-code/sc/NMFMorph.scd
flucoma/doc/templates/schelp_transformer[0].schelp

This PR pulls in the RST updates and SC example code for NMFMorph. 
In order to render the schelp doc appropriately, a new "species" has been introduced: `transformer[0]`. This is named to mirror `transformer[2]`, in which the 2 indicates that it is a transformer with two audio inputs (and an audio output--like all the transformers). 
The 0 in `transformer[0]` indicates that it is a transformer (--it has an audio output--) with zero audio inputs because the inputs are all buffers used for resynthesis.

NMFMorph (& species transformer[0])

---

doc/KNNClassifier.rst

Solves typos mentioned in: https://github.com/flucoma/flucoma-max/issues/244

[Fix] Typos in KNNClassifier

---

flucoma/doc/templates/maxref.xml

Adds some additional templating to the maxref template in order to link to the buffer management tutorial if the client is a buffer one.
Is contingent on:
https://github.com/flucoma/flucoma-max/pull/300

[docs] Buffer clients link to buffer management tutorial

---

doc/BufAmpFeature.rst
doc/BufChroma.rst
doc/BufLoudness.rst
doc/BufMFCC.rst
doc/BufMelBands.rst
doc/BufNoveltyFeature.rst
doc/BufOnsetFeature.rst
doc/BufPitch.rst
doc/BufSTFT.rst
doc/BufSpectralShape.rst
doc/NoveltySlice.rst

As demonstrated in https://github.com/flucoma/flucoma-docs/issues/126, the layout of the padding text is not great for quickly grabbing what you want to know about the 3 behaviours.
This PR makes a straightforward adjustment to the layout of the text in the docs using an :enum: instead of a block of raw text.
This makes it render as such:
which is consistent with other places such as `fluid.noveltyslice~`:

[enhance] padding layout

---

doc/BufMFCC.rst
doc/BufSineFeature.rst
doc/BufStats.rst
doc/MFCC.rst
doc/SineFeature.rst
example-code/sc/BufMFCC.scd
example-code/sc/BufSineFeature.scd
example-code/sc/MDS.scd
example-code/sc/MFCC.scd
example-code/sc/Normalize.scd
example-code/sc/PCA.scd
example-code/sc/SineFeature.scd
example-code/sc/Standardize.scd
include/FluidParameterDump.hpp

@tedmoore again just for info - one math error, but the rest is just for clarity

Remove inlining in examples

---

doc/DataSet.rst
doc/KDTree.rst
example-code/sc/DataSet.scd

DataSet kNearest doc and example code

bruteforce DataSet kNearest doc and example code

---

doc/DataSetQuery.rst

see related PRs in all repos (core, docs, sc, max, pd)

removes the word rows from the interface of dsquery.limit

---

include/FluidParameterDump.hpp

adjusts `#include`s of flucoma-core headers for the correspondingly named PR branch on core: https://github.com/flucoma/flucoma-core/pull/297

update flucoma core includes
