flucoma/flucoma-docs

doc/Grid.yaml

Updates the text of Grid which was, IMO, too wordy and compacted too much info into the description. I took the liberty of moving much of the more detailed stuff to the discussion instead.﻿

[Docs] Grid Documentation

---

doc/KDTree.yaml

Documents and closes https://github.com/flucoma/flucoma-sc/issues/35

KDTree returns symbol

---

flucoma/doc/pd/driver.py

This fixes #33 by not applying ~ to data object names

make pd_object_namer more discriminating

---

doc/UMAP.yaml

This was prompted to me by the SCDoc render, and there's more where that came from, so before I dig in, just want to make sure I'm not missing anything. 
Is this the right idea for fixing missing stuff in the yaml?

added method 'transformPoint' to UMAP.yaml

---

doc/HPSS.yaml

This will close https://github.com/flucoma/flucoma-docs/issues/58.
Also, please take look at the language that is now included. If there are any suggestions I'll be happy to implement, since we're taking a moment to notice this anyway.
If approved, please merge!

HPSS yaml: combined the 2 `discussion` sections into 1

---

flucoma/doc/sc/defaults.py
flucoma/doc/sc/driver.py

@tedmoore  fixes #61 possibly 
Catches the `harmThresh` and `percThresh` params and expands these out (hopefully in the right place) to separate args 😭 😭 
If this does the trick for you, approve and merge...

💩  expand out freq-amp pair compound params for SCdoc

---

doc/KDTree.yaml

Updates﻿ the documentation to solve problems noted in https://github.com/flucoma/flucoma-docs/issues/28.
@tedmoore would you be up for doing a one pass on the changes and approving or suggesting changes?
If you're happy go ahead and merge and also close the linked issue.

[Docs] KDTree documentation update

---

doc/UMAP.yaml

Cleans up the delineation between discussion and description making the description much smaller and tighter.﻿

[Docs] UMAP Docs

---

doc/BufScale.yaml

I've updated the description and discussion separation for BufScale as it was all in the discussion before. I hope this is still clear for what the object does. @tremblap could you quickly take a look and if happy merge?﻿

[Docs] BufScale

---

doc/BufFlatten.rst
doc/BufMelBands.rst
doc/BufNMF.rst
doc/BufNMFCross.rst
doc/BufSelectEvery.rst
doc/KDTree.rst
doc/KMeans.rst
doc/MLPClassifier.rst
doc/MLPRegressor.rst
doc/NMFMorph.rst

remainder of single backtick replaced.

first pass at removing all single quote

---

doc/KMeans.rst

Updates the KMeans docs﻿.
Mind taking a look @tedmoore. It may be too technical with the *equal variance*.

[Docs] KMeans Docs

---

flucoma/doc/templates/cli_htmlref.html

@jamesb93 this adds rendering for parameter enum values to the  CLI docs

render enum controls in cli docs

---

flucoma/doc/templates/schelp_controls.schelp

Add enum rendering to SC control jinja template

---

doc/Stats.rst

Changes the size parameter to history.

[Fix] @size to @history for fluid.stats

---

flucoma/doc/templates/pd_htmlref.html

Adds some basic CSS to improve the aesthetic of the reference HTML for PureData

[enhance] CSS for PD HTML

---

flucoma/doc/pd/driver.py

PD: Correct naming of fluid.stats

---

include/FluidParameterDump.hpp

Supports https://github.com/flucoma/flucoma-core/pull/190

ParamDump: add overload for allocator-aware string

---

doc/KNNRegressor.rst
example-code/sc/KNNRegressor.scd

goes with the similarily named PR in core

amended KNNregressor to multi-multi interface

---

doc/KNNRegressor.rst
example-code/sc/KDTree.scd
example-code/sc/KNNRegressor.scd

1.0.6 preprod to prod

---

example-code/sc/SineFeature.scd

relating to flucoma-sc PR#166 - fixes a discrepency between this objects and all the others (and its own doc!)

sinefeature example has the interface is says it has

---

flucoma/doc/templates/maxref.xml

adds a simple explanation of the new execution priority in max for read and write

explanation in Max doc's read/write deferlow execution

---

example-code/sc/DataSet.scd

first iteration of example code for datasetread
